### ISSUE TITLE
Add qualifying results section

### ISSUE THREAD

**Issue by smolovk** [halldorstefans/f1-cli#1]
Hello!

Nice tool, i intend to use it as my zsh startup screen, but it lacks qualifying results. Would be great if those are added, and used ergast api supports them. I could add them myself, if you can merge my PR and deploy changes to pip (not sure how the last thing is done).

**Comment by smolovk** [comment]
i cant understand how this setup.py toolchain is working, so if you can, please, add quali functionality.

**Comment by smolovk** [comment]
https://ergast.com/mrd/methods/qualifying/ here is the docs page

**Comment by halldorstefans** [comment]
Hi @smolovk,

Thank you for your interest in my tool and I'm flattered that you intend to use it regularly.

I'll do my best to add it before next season starts. I'm hoping I can find time around Christmas to make the necessary changes.

**Comment by halldorstefans** [comment]
Qualifying section has been added and published.
See [pypi](https://pypi.org/project/formula1-cli/0.2.0/).

Note that the [underlying API](https://ergast.com/mrd/) has been deprecated, so this tool won't work beyond 2024.
